#!/usr/bin/env bash
#PBS -l walltime=01:45:05
#PBS -l mem=3gb
#PBS -N KPI1d
#PBS -m n
echo "Hello ${1} $2 $3"
#S1B wv2 YYYYMMDD
myvariable=$(whoami)
pybin=/home1/datawork/agrouaze/conda_envs/py3_dev_datawork/bin/python

if [[ "${myvariable}" == "agrouaze" ]]; then
  echo 'je suis agrouaze'

  export PYTHONPATH=/home1/datahome/agrouaze/git/kpi_mpc/:$PYTHONPATH
  export PYTHONPATH=/home1/datahome/agrouaze/git/mpc/data_collect/:$PYTHONPATH
  export PYTHONPATH=/home1/datahome/agrouaze/git/mpc/qualitycheck/:$PYTHONPATH
  pyexe=/home1/datahome/agrouaze/git/kpi_mpc/src/kpi_WV_hs/compute_kpi_1d_v2.py
  pyexe=/home1/datahome/agrouaze/git/kpi_mpc/src/kpi_WV_hs/compute_kpi_1d_v8.py
else
  echo 'je suis : '$myvariable
  export PYTHONPATH=/home1/datahome/satwave/sources_en_exploitation2/kpi_mpc/:$PYTHONPATH
  export PYTHONPATH=/home1/datahome/satwave/sources_en_exploitation2/mpc/data_collect/:$PYTHONPATH
  export PYTHONPATH=/home1/datahome/satwave/sources_en_exploitation2/mpc/qualitycheck/:$PYTHONPATH
  pyexe=/home1/datahome/satwave/sources_en_exploitation2/kpi_mpc/src/kpi_WV_hs/compute_kpi_1d_v8.py
fi;
#$pybin $pyexe --satellite $1 --wv $2 --enddate $3 --version test9 --overwrite
$pybin $pyexe --satellite $1 --wv $2 --enddate $3 --overwrite
echo end of python script exe
exit 0
